Web_projekat/Controllers/ApartmentController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_projekat.Models;
using Web_projekat.Models.User;

namespace Web_projekat.Controllers
{
    public class ApartmentController : Controller
    {

        DataAccessLayer dal = new DataAccessLayer();
       

        #region Convert HttpPostedFileBase to byte array
        public byte[] ConvertToByte(HttpPostedFileBase file)
        {
            byte[] imageByte = null;
            BinaryReader rdr = new BinaryReader(file.InputStream);
            imageByte = rdr.ReadBytes((int)file.ContentLength);
            return imageByte;
        }
        #endregion

        // GET: Apartment
        public ActionResult HostViewApartments()
        {
            return View();
        }

        public ActionResult HostAddApartment()
        {
            ViewBag.basic = dal.availableamenitiesdb.Where(x => x.type == 1).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            ViewBag.family = dal.availableamenitiesdb.Where(x => x.type == 2).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            ViewBag.facility = dal.availableamenitiesdb.Where(x => x.type == 3).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            ViewBag.dining = dal.availableamenitiesdb.Where(x => x.type == 4).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            return View();
        }


        #region Add Apartment
        [HttpPost]
        public ActionResult AddApartment(Apartment apartment, Dictionary<string, string> list, List<HttpPostedFileBase> imageUpload, List<string> amenitybasic,
            List<string> amenityfamily, List<string> amenityfacility, string tajp ,List<string> amenitydining, Location location, Address address)
        {
            User sc = (User)Session["user"];

            Apartment ap = new Apartment();
            ap.images = new List<Photo>();
            Location loc = new Location();
            Address ad = new Address();
            ap.amenities = new List<Amenity>();
            if (tajp == "room")
            {
                ap.type = Models.Type.Room;
            }
            else
            {
                ap.type = Models.Type.Apartment;

            }
            ap.User = dal.usersdb.FirstOrDefault(g => g.username == sc.username);
            ap.UserId = dal.usersdb.FirstOrDefault(g => g.username == sc.username).UserId;
            ap.number_of_guests = apartment.number_of_guests;
            ap.Times = new DateTimeCollection();
            ap.number_of_rooms = apartment.number_of_rooms;
            ap.price_per_night = apartment.price_per_night;

            loc.Apartment = ap;
            loc.latitude = location.latitude;
            loc.longitude = location.longitude;


            ad.Location = loc;
            ad.number = address.number;
            ad.street = address.street;
            ad.postal_code = address.postal_code;
            ad.city = address.city;

            loc.Address = ad;

            ap.Location = loc;

            

            List<string> templista = new List<string>();
            foreach(string str in list.Keys)
            {
                templista.Add(str);
            }
            ap.Times.AddRange(templista);
            ap.Times = ap.Times;
            if (imageUpload[0] != null)
            {
                foreach (HttpPostedFileBase image in imageUpload)
                {
                    Photo photo = new Photo();
                    photo.ApartmentId = ap.ApartmentId;
                    photo.Apartment = ap;
                    photo.Description = image.FileName;
                    photo.ImageBytes = ConvertToByte(image);
                    ap.images.Add(photo);
                }
            }
            if (amenitybasic != null)
            {
                foreach (string basic in amenitybasic)
                {
                    Amenity amenity = new Amenity();
                    amenity.Apartment = ap;
                    amenity.ApartmentId = ap.ApartmentId;
                    amenity.name = basic;
                    amenity.type = 1;
                    ap.amenities.Add(amenity);
                }
            }
            if (amenityfamily != null)
            {
                foreach (string basic in amenityfamily)
                {
                    Amenity amenity = new Amenity();
                    amenity.Apartment = ap;
                    amenity.ApartmentId = ap.ApartmentId;
                    amenity.name = basic;
                    amenity.type = 2;
                    ap.amenities.Add(amenity);
                }
            }
            if (amenityfacility != null)
            {
                foreach (string basic in amenityfacility)
                {
                    Amenity amenity = new Amenity();
                    amenity.Apartment = ap;
                    amenity.ApartmentId = ap.ApartmentId;
                    amenity.name = basic;
                    amenity.type = 3;
                    ap.amenities.Add(amenity);
                }
            }
            if (amenitydining != null)
            {
                foreach (string basic in amenitydining)
                {
                    Amenity amenity = new Amenity();
                    amenity.Apartment = ap;
                    amenity.ApartmentId = ap.ApartmentId;
                    amenity.name = basic;
                    amenity.type = 4;
                    ap.amenities.Add(amenity);
                }
            }

            sc.apartments.Add(ap);
            dal.apartmentsdb.Add(ap);
            try
            {
                dal.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return RedirectToAction("HostViewApartments");
        }
        #endregion

        public ActionResult AdminInactiveApartments()
        {
            List<User> lista = new List<User>();

            foreach (User u in dal.usersdb.ToDictionary(x => x.username, x => x).Values)
            {

                if ((string)Session["filterbystatus"] == "active")
                {
                    u.apartments = dal.apartmentsdb.Select(x => x).Where(x => x.UserId == u.UserId).Where(x => x.active == true).ToList();

                }
                else if ((string)Session["filterbystatus"] == "inactive")
                {

                    u.apartments = dal.apartmentsdb.Select(x => x).Where(x => x.UserId == u.UserId).Where(x => x.active == false).ToList();
                }

                foreach (Apartment ap in u.apartments)
                {
                    ap.images = dal.photosdb.Select(x => x).Where(x => x.ApartmentId == ap.ApartmentId).ToList();
                    ap.amenities = dal.amenitiesdb.Select(x => x).Where(x => x.ApartmentId == ap.ApartmentId).ToList();
                }



                lista.Add(u);
            }

            ViewBag.lista = lista;

            return View();
        }

        [HttpPost]
        public ActionResult AdminInactiveApartments(string active, int id)
        {

            User sc = (User)Session["user"];

            if (active == "Active")
                dal.apartmentsdb.ToDictionary(x => x.ApartmentId, x => x)[id].active = true;
            else
            {
                dal.apartmentsdb.ToDictionary(x => x.ApartmentId, x => x)[id].active = false;

            }

            dal.SaveChanges();


            Session["user"] = sc;

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult ChangeApartment(int apartmentid, int userid)
        {
            ViewBag.basic = dal.availableamenitiesdb.Where(x => x.type == 1).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            ViewBag.family = dal.availableamenitiesdb.Where(x => x.type == 2).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            ViewBag.facility = dal.availableamenitiesdb.Where(x => x.type == 3).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();
            ViewBag.dining = dal.availableamenitiesdb.Where(x => x.type == 4).Where(x => x.IsDeleted == false).Select(x => x.name).ToList();

            User u = dal.usersdb.ToDictionary(x => x.UserId, x => x)[userid];
            Apartment ap = dal.apartmentsdb.ToDictionary(x => x.ApartmentId, x => x)[apartmentid];
            ap.images = new List<Photo>();
            ap.amenities = new List<Amenity>();
            

            ap.amenities = dal.amenitiesdb.Where(x => x.ApartmentId == ap.ApartmentId).Where(x => x.IsDeleted == false).Select(x => x).ToList();
            ap.images = dal.photosdb.Where(x => x.ApartmentId == ap.ApartmentId).Select(x => x).ToList();
            

            ViewBag.ap = ap;

            return View();
        }

        [HttpPost]
        public ActionResult Change(Apartment apartment, Dictionary<string, string> list, List<HttpPostedFileBase> imageUpload, List<string> amenitybasic,

Web_projekat/Controllers/UserOperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_projekat.Models;
using Web_projekat.Models.User;

namespace Web_projekat.Controllers
{
    public class UserOperationsController : Controller
    {

        DataAccessLayer dal = new DataAccessLayer();

        // GET: UserOperations
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {

            return View();
        }

        public ActionResult FailedRegister()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registerr(User user)
        {

            bool exist = false;
            Dictionary<string, User> tempdict = dal.usersdb.ToDictionary(x => x.username, x => x);

            foreach(User tempuser in tempdict.Values)
            {
                if(tempuser.username == user.username)
                {
                    exist = true;
                    ViewBag.username = tempuser.username;
                    break;
                }
            }

            if(exist)
            {
                return View("FailedRegister");
            }

            User sc = new User();
            sc.apartments = new List<Models.Apartment>();

            int cnt = dal.usersdb.Count();

            sc.UserId = cnt++;
            sc.email = user.email;
            sc.name = user.name;
            sc.username = user.username;
            sc.password = user.password;
            sc.surname = user.surname;
            sc.sex = user.sex;
            sc.role = user.role;

            Session["user"] = sc;   

            
            
            ViewBag.user = user;

            dal.usersdb.Add(user);
            dal.SaveChanges();

            return Redirect(Url.Content("~/"));
        }

        public ActionResult AdminViewUsers()
        {
            ViewBag.registrovani = dal.usersdb.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult LoginCheck(string username, string password)
        {
            bool login = false;


            User sc = (User)Session["user"];
            Admins admini = (Admins)HttpContext.Application["admini"];
            foreach(User u in admini.admini.Values)
            {
                if(u.username == username && u.password == password)
                {
                    sc = u;
                    Session["user"] = sc;
                    ViewBag.user = sc;
                    login = true;
                    break;
                }
            }

            foreach(User u in dal.usersdb.ToList())
            {
                if (u.username == username && u.password == password)
                {
                    sc = u;
                    Session["user"] = sc;
                    ViewBag.user = sc;
                    login = true;
                    break;
                }
            }

            if(!login)
            {
              return RedirectToAction("FailedLogin");
            }

            ViewBag.users = dal.usersdb.ToList();


            List<Apartment> lista = new List<Apartment>();

            foreach (Apartment ap in dal.apartmentsdb.ToDictionary(x => x.ApartmentId, x => x).Values)
            {
                foreach (Photo ph in dal.photosdb.ToDictionary(x => x.PhotoId, x => x).Values)
                {
                    if (ap.ApartmentId == ph.ApartmentId)
                    {
                        ap.images.Add(ph);
                    }
                }

                if (ap.UserId == sc.UserId)
                {
                    lista.Add(ap);
                }

            }


            sc.apartments = lista;

            if (login)
            {
                return Redirect(Url.Content("~/"));

            }
            else
                return Redirect(Url.Content("~/"));

        }

        public ActionResult FailedLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminChangeRole(User user, string role)
        {

            dal.usersdb.ToDictionary(x => x.username, x => x)[user.username].role = user.role;
            dal.SaveChanges();
            TempData["notice"] = "Successfully changed";

            return RedirectToAction("AdminViewUsers");
        }

        public ActionResult UserChangeData()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ChangeProfileData(User u)
        {
            User sc = (User)Session["user"];

            dal.usersdb.ToDictionary(x => x.username, x => x)[sc.username].name = u.name;
            dal.usersdb.ToDictionary(x => x.username, x => x)[sc.username].surname = u.surname;
            dal.usersdb.ToDictionary(x => x.username, x => x)[sc.username].email = u.email;
            dal.usersdb.ToDictionary(x => x.username, x => x)[sc.username].password = u.password;
            dal.usersdb.ToDictionary(x => x.username, x => x)[sc.username].sex = u.sex;
            dal.usersdb.ToDictionary(x => x.username, x => x)[sc.username].username = u.username;

            dal.SaveChanges();

            User temp = dal.usersdb.Where(x => x.UserId == sc.UserId).Select(x => x).Single();
            temp.apartments = dal.apartmentsdb.Where(x => x.UserId == sc.UserId).Select(x => x).ToList();
            foreach (Apartment ap in temp.apartments)
            {          
                ap.images = dal.photosdb.Where(x => x.ApartmentId == ap.ApartmentId).Select(x => x).ToList();
                ap.amenities = dal.amenitiesdb.Where(x => x.ApartmentId == ap.ApartmentId).Select(x => x).ToList();
            }

            Session["user"] = temp;

            return Redirect(Url.Content("~/"));
        }

        public ActionResult LogOut()
        {
            Session.Remove("user");
            return Redirect(Url.Content("~/"));

        } 
    }
}

Web_projekat/Views/Shared/Layouts/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,800' rel='stylesheet'>

</head>
<body>
    <div class="header">
        <div class="innerheader">
            <div class="logo_container">
                <h1>@Html.ActionLink("MySite", "Index", "Home", null, new { @style = "color:red;" })</h1>
            </div>

            <ul class="navigation">
                <li>@Html.ActionLink("Users", "AdminViewUsers", "UserOperations")</li>
                <li>@Html.ActionLink("Inactive Apartments", "AdminInactiveApartments", "Apartment")</li>
                <li><a>@Html.ActionLink("Amenities", "AdminChangeAmenities", "Apartment")</a></li>
                <li><a>@Html.ActionLink("Log Out", "Logout", "UserOperations")</a></li>
            </ul>
        </div>
    </div>
    <div class="bg-image"></div>


    <div class="container body-content">
        @RenderBody()
    </div>

    <style>
        .navigation li .klasa {
            font-size: x-large;
            color: red;
        }

        .disableButton {
            background: #eee;
            color: #444;
        }

        .name {
            text-align: left;
            width: 70%;
            margin: 10% auto 0;
            border-collapse: separate;
            font-weight: 400;
            position: absolute;
            top: 15%;
            left: 15%;
            right: 15%;
            margin: 0 auto;
            z-index: 2;
        }

        .container {
            text-align: left;
            width: 70%;
            margin: 10% auto 0;
            border-collapse: separate;
            font-weight: 400;
            position: absolute;
            top: 15%;
            left: 15%;
            right: 15%;
            margin: 0 auto;
            z-index: 2;
        }

        * {
            font-family: sans-serif;
        }


        input[type=text], input[type=password], input[type=email] {
            width: 100%;
            border-radius: 10px;
            box-sizing: border-box;
            background: rgb(16,16,16);
            background: linear-gradient(90deg, rgba(16,16,16,1) 14%, rgba(40,36,110,1) 50%, rgba(16,16,16,1) 82%);
            border: none;
            font-weight: 500;
            font-size: 16px;
            outline: none;
            border-bottom: 1px solid white;
            margin: 15px;
            color: wheat;
            padding: 15px 5px;
        }


        input[type=radio] {
            padding: 12px 5px;
            margin: 5px;
            margin-top: 15px;
            color: wheat;
            background-color: black;
        }

        button, input[type=submit] {
            cursor: pointer;
            width: 200px;
            margin-top: 25px;
            margin-left: 60px;
            border-radius: 18px;
            font-size: 25px;
            background: rgb(16,16,16);
            background: linear-gradient(90deg, rgba(16,16,16,1) 14%, rgba(40,36,110,1) 50%, rgba(16,16,16,1) 82%);
            outline: none;
            border: none;
            box-sizing: border-box;
            padding: 5px;
            left: 15%;
            transition-duration: 0.4s;
        }

            button:hover, input[type=submit]:hover {
                background-color: gray;
                color: wheat;
                border: 1px solid wheat;
            }

        .rad {
            font-weight: 400;
            text-align: center;
            margin: 15px;
            margin-top: 20px;
            color: white;
        }

        select {
            width: 25%;
            border-radius: 10px;
            box-sizing: border-box;
            border: none;
            outline: none;
            font-weight: 100;
            font-size: 16px;
            border-bottom: 1px solid white;
            margin: 5px;
            color: white;
            background-color: black;
            padding: 9px 5px;
        }

        .selq {
            width: 100%;
            border-radius: 10px;
            box-sizing: border-box;
            background: black;
            border: none;
            font-weight: 500;
            font-size: 16px;
            outline: none;
            border-bottom: 1px solid white;
            margin: 6px;
            color: gray;
            padding: 12px 5px;
        }
    </style>

    <style>
        body, html {
            height: 100%;
            margin: 0;
            font-family: 'Montserrat';
        }

        .bg-image {
            background-image: url(../Content/1200x-1.jpg);
            background-size: 100%;
            /* The image used */
            /* Add the blur effect */
            filter: blur(5px);
            /* Full height */
            height: 100%;
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .navigation li:last-child {
            padding-right: 0;
        }



        .navigation li a {
            display: table-cell;
            vertical-align: middle;
            height: 100%;
            color: wheat;
            transition: 0.3s;
            font-size: 16px;
        }




            .navigation li a:hover {
                font-size: x-large;
                color: red;
            }

        .navigation li {
            height: 100%;
            display: table;
            float: left;
            padding: 0px 20px;
        }


        .navigation {
            float: right;
            height: 100%;
        }


        .innerheader {
            width: 70%;
            height: 100%;
            display: block;
            margin: 0 auto;
            background: rgb(16,16,16);
            background: linear-gradient(90deg, rgba(16,16,16,1) 14%, rgba(40,36,110,1) 50%, rgba(16,16,16,1) 82%);
        }

        .header {
            width: 100%;
            height: 80px;
            display: block;
            background-color: #101010;
        }

        * {
            margin: 0;
            padding: 0;
            list-style: none;
            text-decoration: none;
        }

        .logo_container {
            height: 100%;
            display: table;
            float: left;
        }

            .logo_container h1 {
                height: 100%;
                display: table-cell;
                vertical-align: middle;
                font-size: 32px;
            }
    </style>
</body>
</html>

Web_projekat/Views/Shared/Layouts/HostLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,800' rel='stylesheet'>
</head>
<body>
    <div class="header">
        <div class="innerheader">
            <div class="logo_container">
                <h1>@Html.ActionLink("MySite", "Index", "Home", null, new { @style = "color:red;" })</h1>
            </div>
            <ul class="navigation">
                <li><a>@Html.ActionLink("Your Profile", "UserChangeData", "UserOperations", new { area = "" }, new { @class = "navbar-brand" })</a></li>
                <li><a>@Html.ActionLink("Apartments", "HostViewApartments", "Apartment", new { area = "" }, new { @class = "navbar-brand" })</a></li>
                <li><a>@Html.ActionLink("Log Out", "Logout", "UserOperations")</a></li>
            </ul>
        </div>
    </div>
    <div class="bg-image"></div>


    <div class="container body-content">
        @RenderBody()
    </div>

    <style>
        .navigation li .klasa {
            font-size: x-large;
            color: red;
        }

        .disableButton {
            background: #eee;
            color: #444;
        }

        .name {
            text-align: left;
            width: 70%;
            margin: 10% auto 0;
            border-collapse: separate;
            font-weight: 400;
            position: absolute;
            top: 15%;
            left: 15%;
            right: 15%;
            margin: 0 auto;
            z-index: 2;
        }

        .container {
            text-align: left;
            width: 70%;
            margin: 10% auto 0;
            border-collapse: separate;
            font-weight: 400;
            position: absolute;
            top: 15%;
            left: 15%;
            right: 15%;
            margin: 0 auto;
            z-index: 2;
        }

        * {
            font-family: sans-serif;
        }


        input[type=text], input[type=password], input[type=email] {
            width: 100%;
            border-radius: 10px;
            box-sizing: border-box;
            background: rgb(16,16,16);
            background: linear-gradient(90deg, rgba(16,16,16,1) 14%, rgba(40,36,110,1) 50%, rgba(16,16,16,1) 82%);
            border: none;
            font-weight: 500;
            font-size: 16px;
            outline: none;
            border-bottom: 1px solid white;
            margin: 15px;
            color: wheat;
            padding: 15px 5px;
        }


        input[type=radio] {
            padding: 12px 5px;
            margin: 5px;
            margin-top: 15px;
            color: wheat;
            background-color: black;
        }

        button, input[type=submit] {
            cursor: pointer;
            width: 200px;
            margin-top: 25px;
            margin-left: 60px;
            border-radius: 18px;
            font-size: 25px;
            background: rgb(16,16,16);
            background: linear-gradient(90deg, rgba(16,16,16,1) 14%, rgba(40,36,110,1) 50%, rgba(16,16,16,1) 82%);
            outline: none;
            border: none;
            box-sizing: border-box;
            padding: 5px;
            left: 15%;
            transition-duration: 0.4s;
        }

            button:hover, input[type=submit]:hover {
                background-color: gray;
                color: wheat;
                border: 1px solid wheat;
            }

        .rad {
            font-weight: 400;
            text-align: center;
            margin: 15px;
            margin-top: 20px;
            color: white;
        }

        select {
            width: 30%;
            border-radius: 10px;
            box-sizing: border-box;
            border: none;
            outline: none;
            font-weight: 100;
            font-size: 16px;
            border-bottom: 1px solid white;
            margin: 5px;
            color: white;
            background-color: black;
            padding: 9px 5px;
        }

        .selq {
            width: 100%;
            border-radius: 10px;
            box-sizing: border-box;
            background: black;
            border: none;
            font-weight: 500;
            font-size: 16px;
            outline: none;
            border-bottom: 1px solid white;
            margin: 6px;
            color: gray;
            padding: 12px 5px;
        }
    </style>

    <style>
        body, html {
            height: 100%;
            margin: 0;
            font-family: 'Montserrat';
        }

        .bg-image {
            background-image: url(/Content/1200x-1.jpg);
            background-size: 100%;
            /* The image used */
            /* Add the blur effect */
            filter: blur(5px);
            /* Full height */
            height: 100%;
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .navigation li:last-child {
            padding-right: 0;
        }



        .navigation li a {
            display: table-cell;
            vertical-align: middle;
            height: 100%;
            color: wheat;
            transition: 0.3s;
            font-size: 16px;
        }




            .navigation li a:hover {
                font-size: x-large;
                color: red;
            }

        .navigation li {
            height: 100%;
            display: table;
            float: left;
            padding: 0px 20px;
        }


        .navigation {
            float: right;
            height: 100%;
        }


        .innerheader {
            width: 70%;
            height: 100%;
            display: block;
            margin: 0 auto;
            background: rgb(16,16,16);
            background: linear-gradient(90deg, rgba(16,16,16,1) 14%, rgba(40,36,110,1) 50%, rgba(16,16,16,1) 82%);
        }

        .header {
            width: 100%;
            height: 80px;
            display: block;
            background-color: #101010;
        }

        * {
            margin: 0;
            padding: 0;
            list-style: none;
            text-decoration: none;
        }

        .logo_container {
            height: 100%;
            display: table;
            float: left;
        }

            .logo_container h1 {
                height: 100%;
                display: table-cell;
                vertical-align: middle;
                font-size: 32px;
            }
    </style>
</body>
</html>